version: '3'

services:
  flask-app1:
    image: app1_image
    build:
      context: ./app1
    ports:
      - "8085:8085"
    depends_on:
      - flask-app2
  flask-app2:
    image: app2_image
    build:
      context: ./app2
    ports:
      - "8086:8086"
