version: '3'

services:
  flask-app1:
    image: app1_image
    build:
      context: ./app1
    ports:
      - "8088:8088"  # Map the Flask app's port to the host
    depends_on:
      - flask-app2  # Ensure that the app2 is started before app1

  flask-app2:
    image: app2_image
    build:
      context: ./app2
    ports:
      - "8089:8089"  # Map the Flask app's port to the host

