# https://hub.docker.com/_/python/tags
FROM ajithvallabai/flask-torch-001:latest
# FROM python:3.10-slim

# RUN apt update -y && apt-get install ffmpeg libsm6 libxext6  -y
# WORKDIR /app
# EXPOSE 8085
# COPY . /app
# RUN pip3 install -r requirements.txt

# CMD python app.py
# ["tail", "-f", "/dev/null"]
CMD tail -f /dev/null
# dummy command for debugging